# Generated by Django 4.2.5 on 2023-09-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('direccion', models.TextField()),
                ('tipo_almacen', models.CharField(max_length=40)),
                ('fech_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=35, unique=True)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Familia'), (2, 'Grupo'), (3, 'Categoria')])),
                ('fech_creacion', models.DateField(auto_now_add=True)),
                ('cod_grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('cod_lote', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom_lote', models.CharField(max_length=35)),
                ('fech_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('cod_und', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom_und', models.CharField(max_length=25, unique=True)),
                ('fech_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('cod_material', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=60, unique=True)),
                ('descripcion_material', models.TextField()),
                ('con_lote', models.BooleanField(default=False)),
                ('fech_creacion', models.DateField(auto_now_add=True)),
                ('cod_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categoria', verbose_name='categoria')),
                ('umb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unidad', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ubicacion', models.CharField(max_length=60)),
                ('movimiento', models.CharField(max_length=60)),
                ('observacion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('orden_compra', models.CharField(max_length=18, null=True)),
                ('guia', models.CharField(max_length=18, null=True)),
                ('fech_modificacion', models.DateField(auto_now=True)),
                ('fech_creacion', models.DateField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.almacen', verbose_name='almacen')),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unidad', verbose_name='unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_inventario', models.CharField(max_length=12)),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('frecuencia', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('promedio', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('cobertura', models.DecimalField(decimal_places=3, default=1.0, max_digits=12)),
                ('fecha_inventario', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='material')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.CheckConstraint(check=models.Q(('tipo__in', [1, 2, 3])), name='ch_tipo_categoria'),
        ),
    ]
