# Generated by Django 4.2.5 on 2023-09-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_almacen_categoria_lote_unidad_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoria',
            name='ch_tipo_categoria',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_inventario',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='nom_inventario',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='material',
            name='con_lote',
        ),
        migrations.AddField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen', verbose_name='almacen'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fech_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fech_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='meses',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nom_ubicacion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='primer_cuartil',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventario',
            name='segundo_cuartil',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tercer_cuartil',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cobertura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='frecuencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
