# Generated by Django 4.2.5 on 2023-10-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_cod_categoria_material_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion_material',
            field=models.TextField(blank=True, null=True),
        ),
    ]
